/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StandaloneLayoutRouteImport } from './routes/standalone-layout'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthTreeRouteImport } from './routes/_auth/tree'
import { Route as AuthKanbanRouteImport } from './routes/_auth/kanban'
import { Route as AuthSignatureIndexRouteImport } from './routes/_auth/signature/index'
import { Route as AuthSchedulerIndexRouteImport } from './routes/_auth/scheduler/index'
import { Route as AuthLayoutImperativeIndexRouteImport } from './routes/_auth/layout-imperative/index'
import { Route as AuthKanbanIndexRouteImport } from './routes/_auth/kanban/index'
import { Route as AuthTableVariantsRouteImport } from './routes/_auth/table/variants'
import { Route as AuthTablePivotRouteImport } from './routes/_auth/table/pivot'
import { Route as AuthTableGroupingRouteImport } from './routes/_auth/table/grouping'
import { Route as AuthTableCrudRouteImport } from './routes/_auth/table/crud'
import { Route as AuthTableColumnTypesRouteImport } from './routes/_auth/table/column-types'
import { Route as AuthTableBasicTableRouteImport } from './routes/_auth/table/basic-table'
import { Route as AuthTableAllTypesRouteImport } from './routes/_auth/table/all-types'
import { Route as AuthSchedulerWorkdaysRouteImport } from './routes/_auth/scheduler/workdays'
import { Route as AuthSchedulerViewsRouteImport } from './routes/_auth/scheduler/views'
import { Route as AuthSchedulerTimelineRouteImport } from './routes/_auth/scheduler/timeline'
import { Route as AuthSchedulerResourceRouteImport } from './routes/_auth/scheduler/resource'
import { Route as AuthSchedulerGroupingRouteImport } from './routes/_auth/scheduler/grouping'
import { Route as AuthSchedulerEnhancementsRouteImport } from './routes/_auth/scheduler/enhancements'
import { Route as AuthKanbanTimelineRouteImport } from './routes/_auth/kanban/timeline'
import { Route as AuthKanbanSwimlanesRouteImport } from './routes/_auth/kanban/swimlanes'
import { Route as AuthKanbanEventsRouteImport } from './routes/_auth/kanban/events'
import { Route as AuthKanbanCustomizationRouteImport } from './routes/_auth/kanban/customization'
import { Route as AuthKanbanBasicRouteImport } from './routes/_auth/kanban/basic'
import { Route as AuthDocsEzLayoutRouteImport } from './routes/_auth/docs/ez-layout'

const StandaloneLayoutRoute = StandaloneLayoutRouteImport.update({
  id: '/standalone-layout',
  path: '/standalone-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTreeRoute = AuthTreeRouteImport.update({
  id: '/tree',
  path: '/tree',
  getParentRoute: () => AuthRoute,
} as any)
const AuthKanbanRoute = AuthKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignatureIndexRoute = AuthSignatureIndexRouteImport.update({
  id: '/signature/',
  path: '/signature/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSchedulerIndexRoute = AuthSchedulerIndexRouteImport.update({
  id: '/scheduler/',
  path: '/scheduler/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLayoutImperativeIndexRoute =
  AuthLayoutImperativeIndexRouteImport.update({
    id: '/layout-imperative/',
    path: '/layout-imperative/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthKanbanIndexRoute = AuthKanbanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthKanbanRoute,
} as any)
const AuthTableVariantsRoute = AuthTableVariantsRouteImport.update({
  id: '/table/variants',
  path: '/table/variants',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTablePivotRoute = AuthTablePivotRouteImport.update({
  id: '/table/pivot',
  path: '/table/pivot',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTableGroupingRoute = AuthTableGroupingRouteImport.update({
  id: '/table/grouping',
  path: '/table/grouping',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTableCrudRoute = AuthTableCrudRouteImport.update({
  id: '/table/crud',
  path: '/table/crud',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTableColumnTypesRoute = AuthTableColumnTypesRouteImport.update({
  id: '/table/column-types',
  path: '/table/column-types',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTableBasicTableRoute = AuthTableBasicTableRouteImport.update({
  id: '/table/basic-table',
  path: '/table/basic-table',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTableAllTypesRoute = AuthTableAllTypesRouteImport.update({
  id: '/table/all-types',
  path: '/table/all-types',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSchedulerWorkdaysRoute = AuthSchedulerWorkdaysRouteImport.update({
  id: '/scheduler/workdays',
  path: '/scheduler/workdays',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSchedulerViewsRoute = AuthSchedulerViewsRouteImport.update({
  id: '/scheduler/views',
  path: '/scheduler/views',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSchedulerTimelineRoute = AuthSchedulerTimelineRouteImport.update({
  id: '/scheduler/timeline',
  path: '/scheduler/timeline',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSchedulerResourceRoute = AuthSchedulerResourceRouteImport.update({
  id: '/scheduler/resource',
  path: '/scheduler/resource',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSchedulerGroupingRoute = AuthSchedulerGroupingRouteImport.update({
  id: '/scheduler/grouping',
  path: '/scheduler/grouping',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSchedulerEnhancementsRoute =
  AuthSchedulerEnhancementsRouteImport.update({
    id: '/scheduler/enhancements',
    path: '/scheduler/enhancements',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthKanbanTimelineRoute = AuthKanbanTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AuthKanbanRoute,
} as any)
const AuthKanbanSwimlanesRoute = AuthKanbanSwimlanesRouteImport.update({
  id: '/swimlanes',
  path: '/swimlanes',
  getParentRoute: () => AuthKanbanRoute,
} as any)
const AuthKanbanEventsRoute = AuthKanbanEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthKanbanRoute,
} as any)
const AuthKanbanCustomizationRoute = AuthKanbanCustomizationRouteImport.update({
  id: '/customization',
  path: '/customization',
  getParentRoute: () => AuthKanbanRoute,
} as any)
const AuthKanbanBasicRoute = AuthKanbanBasicRouteImport.update({
  id: '/basic',
  path: '/basic',
  getParentRoute: () => AuthKanbanRoute,
} as any)
const AuthDocsEzLayoutRoute = AuthDocsEzLayoutRouteImport.update({
  id: '/docs/ez-layout',
  path: '/docs/ez-layout',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/standalone-layout': typeof StandaloneLayoutRoute
  '/kanban': typeof AuthKanbanRouteWithChildren
  '/tree': typeof AuthTreeRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/docs/ez-layout': typeof AuthDocsEzLayoutRoute
  '/kanban/basic': typeof AuthKanbanBasicRoute
  '/kanban/customization': typeof AuthKanbanCustomizationRoute
  '/kanban/events': typeof AuthKanbanEventsRoute
  '/kanban/swimlanes': typeof AuthKanbanSwimlanesRoute
  '/kanban/timeline': typeof AuthKanbanTimelineRoute
  '/scheduler/enhancements': typeof AuthSchedulerEnhancementsRoute
  '/scheduler/grouping': typeof AuthSchedulerGroupingRoute
  '/scheduler/resource': typeof AuthSchedulerResourceRoute
  '/scheduler/timeline': typeof AuthSchedulerTimelineRoute
  '/scheduler/views': typeof AuthSchedulerViewsRoute
  '/scheduler/workdays': typeof AuthSchedulerWorkdaysRoute
  '/table/all-types': typeof AuthTableAllTypesRoute
  '/table/basic-table': typeof AuthTableBasicTableRoute
  '/table/column-types': typeof AuthTableColumnTypesRoute
  '/table/crud': typeof AuthTableCrudRoute
  '/table/grouping': typeof AuthTableGroupingRoute
  '/table/pivot': typeof AuthTablePivotRoute
  '/table/variants': typeof AuthTableVariantsRoute
  '/kanban/': typeof AuthKanbanIndexRoute
  '/layout-imperative/': typeof AuthLayoutImperativeIndexRoute
  '/scheduler/': typeof AuthSchedulerIndexRoute
  '/signature/': typeof AuthSignatureIndexRoute
}
export interface FileRoutesByTo {
  '/standalone-layout': typeof StandaloneLayoutRoute
  '/tree': typeof AuthTreeRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/': typeof AuthIndexRoute
  '/docs/ez-layout': typeof AuthDocsEzLayoutRoute
  '/kanban/basic': typeof AuthKanbanBasicRoute
  '/kanban/customization': typeof AuthKanbanCustomizationRoute
  '/kanban/events': typeof AuthKanbanEventsRoute
  '/kanban/swimlanes': typeof AuthKanbanSwimlanesRoute
  '/kanban/timeline': typeof AuthKanbanTimelineRoute
  '/scheduler/enhancements': typeof AuthSchedulerEnhancementsRoute
  '/scheduler/grouping': typeof AuthSchedulerGroupingRoute
  '/scheduler/resource': typeof AuthSchedulerResourceRoute
  '/scheduler/timeline': typeof AuthSchedulerTimelineRoute
  '/scheduler/views': typeof AuthSchedulerViewsRoute
  '/scheduler/workdays': typeof AuthSchedulerWorkdaysRoute
  '/table/all-types': typeof AuthTableAllTypesRoute
  '/table/basic-table': typeof AuthTableBasicTableRoute
  '/table/column-types': typeof AuthTableColumnTypesRoute
  '/table/crud': typeof AuthTableCrudRoute
  '/table/grouping': typeof AuthTableGroupingRoute
  '/table/pivot': typeof AuthTablePivotRoute
  '/table/variants': typeof AuthTableVariantsRoute
  '/kanban': typeof AuthKanbanIndexRoute
  '/layout-imperative': typeof AuthLayoutImperativeIndexRoute
  '/scheduler': typeof AuthSchedulerIndexRoute
  '/signature': typeof AuthSignatureIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/standalone-layout': typeof StandaloneLayoutRoute
  '/_auth/kanban': typeof AuthKanbanRouteWithChildren
  '/_auth/tree': typeof AuthTreeRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/docs/ez-layout': typeof AuthDocsEzLayoutRoute
  '/_auth/kanban/basic': typeof AuthKanbanBasicRoute
  '/_auth/kanban/customization': typeof AuthKanbanCustomizationRoute
  '/_auth/kanban/events': typeof AuthKanbanEventsRoute
  '/_auth/kanban/swimlanes': typeof AuthKanbanSwimlanesRoute
  '/_auth/kanban/timeline': typeof AuthKanbanTimelineRoute
  '/_auth/scheduler/enhancements': typeof AuthSchedulerEnhancementsRoute
  '/_auth/scheduler/grouping': typeof AuthSchedulerGroupingRoute
  '/_auth/scheduler/resource': typeof AuthSchedulerResourceRoute
  '/_auth/scheduler/timeline': typeof AuthSchedulerTimelineRoute
  '/_auth/scheduler/views': typeof AuthSchedulerViewsRoute
  '/_auth/scheduler/workdays': typeof AuthSchedulerWorkdaysRoute
  '/_auth/table/all-types': typeof AuthTableAllTypesRoute
  '/_auth/table/basic-table': typeof AuthTableBasicTableRoute
  '/_auth/table/column-types': typeof AuthTableColumnTypesRoute
  '/_auth/table/crud': typeof AuthTableCrudRoute
  '/_auth/table/grouping': typeof AuthTableGroupingRoute
  '/_auth/table/pivot': typeof AuthTablePivotRoute
  '/_auth/table/variants': typeof AuthTableVariantsRoute
  '/_auth/kanban/': typeof AuthKanbanIndexRoute
  '/_auth/layout-imperative/': typeof AuthLayoutImperativeIndexRoute
  '/_auth/scheduler/': typeof AuthSchedulerIndexRoute
  '/_auth/signature/': typeof AuthSignatureIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/standalone-layout'
    | '/kanban'
    | '/tree'
    | '/auth/signin'
    | '/auth/signup'
    | '/docs/ez-layout'
    | '/kanban/basic'
    | '/kanban/customization'
    | '/kanban/events'
    | '/kanban/swimlanes'
    | '/kanban/timeline'
    | '/scheduler/enhancements'
    | '/scheduler/grouping'
    | '/scheduler/resource'
    | '/scheduler/timeline'
    | '/scheduler/views'
    | '/scheduler/workdays'
    | '/table/all-types'
    | '/table/basic-table'
    | '/table/column-types'
    | '/table/crud'
    | '/table/grouping'
    | '/table/pivot'
    | '/table/variants'
    | '/kanban/'
    | '/layout-imperative/'
    | '/scheduler/'
    | '/signature/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/standalone-layout'
    | '/tree'
    | '/auth/signin'
    | '/auth/signup'
    | '/'
    | '/docs/ez-layout'
    | '/kanban/basic'
    | '/kanban/customization'
    | '/kanban/events'
    | '/kanban/swimlanes'
    | '/kanban/timeline'
    | '/scheduler/enhancements'
    | '/scheduler/grouping'
    | '/scheduler/resource'
    | '/scheduler/timeline'
    | '/scheduler/views'
    | '/scheduler/workdays'
    | '/table/all-types'
    | '/table/basic-table'
    | '/table/column-types'
    | '/table/crud'
    | '/table/grouping'
    | '/table/pivot'
    | '/table/variants'
    | '/kanban'
    | '/layout-imperative'
    | '/scheduler'
    | '/signature'
  id:
    | '__root__'
    | '/_auth'
    | '/standalone-layout'
    | '/_auth/kanban'
    | '/_auth/tree'
    | '/auth/signin'
    | '/auth/signup'
    | '/_auth/'
    | '/_auth/docs/ez-layout'
    | '/_auth/kanban/basic'
    | '/_auth/kanban/customization'
    | '/_auth/kanban/events'
    | '/_auth/kanban/swimlanes'
    | '/_auth/kanban/timeline'
    | '/_auth/scheduler/enhancements'
    | '/_auth/scheduler/grouping'
    | '/_auth/scheduler/resource'
    | '/_auth/scheduler/timeline'
    | '/_auth/scheduler/views'
    | '/_auth/scheduler/workdays'
    | '/_auth/table/all-types'
    | '/_auth/table/basic-table'
    | '/_auth/table/column-types'
    | '/_auth/table/crud'
    | '/_auth/table/grouping'
    | '/_auth/table/pivot'
    | '/_auth/table/variants'
    | '/_auth/kanban/'
    | '/_auth/layout-imperative/'
    | '/_auth/scheduler/'
    | '/_auth/signature/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  StandaloneLayoutRoute: typeof StandaloneLayoutRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/standalone-layout': {
      id: '/standalone-layout'
      path: '/standalone-layout'
      fullPath: '/standalone-layout'
      preLoaderRoute: typeof StandaloneLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/tree': {
      id: '/_auth/tree'
      path: '/tree'
      fullPath: '/tree'
      preLoaderRoute: typeof AuthTreeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/kanban': {
      id: '/_auth/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AuthKanbanRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signature/': {
      id: '/_auth/signature/'
      path: '/signature'
      fullPath: '/signature/'
      preLoaderRoute: typeof AuthSignatureIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/scheduler/': {
      id: '/_auth/scheduler/'
      path: '/scheduler'
      fullPath: '/scheduler/'
      preLoaderRoute: typeof AuthSchedulerIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/layout-imperative/': {
      id: '/_auth/layout-imperative/'
      path: '/layout-imperative'
      fullPath: '/layout-imperative/'
      preLoaderRoute: typeof AuthLayoutImperativeIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/kanban/': {
      id: '/_auth/kanban/'
      path: '/'
      fullPath: '/kanban/'
      preLoaderRoute: typeof AuthKanbanIndexRouteImport
      parentRoute: typeof AuthKanbanRoute
    }
    '/_auth/table/variants': {
      id: '/_auth/table/variants'
      path: '/table/variants'
      fullPath: '/table/variants'
      preLoaderRoute: typeof AuthTableVariantsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/table/pivot': {
      id: '/_auth/table/pivot'
      path: '/table/pivot'
      fullPath: '/table/pivot'
      preLoaderRoute: typeof AuthTablePivotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/table/grouping': {
      id: '/_auth/table/grouping'
      path: '/table/grouping'
      fullPath: '/table/grouping'
      preLoaderRoute: typeof AuthTableGroupingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/table/crud': {
      id: '/_auth/table/crud'
      path: '/table/crud'
      fullPath: '/table/crud'
      preLoaderRoute: typeof AuthTableCrudRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/table/column-types': {
      id: '/_auth/table/column-types'
      path: '/table/column-types'
      fullPath: '/table/column-types'
      preLoaderRoute: typeof AuthTableColumnTypesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/table/basic-table': {
      id: '/_auth/table/basic-table'
      path: '/table/basic-table'
      fullPath: '/table/basic-table'
      preLoaderRoute: typeof AuthTableBasicTableRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/table/all-types': {
      id: '/_auth/table/all-types'
      path: '/table/all-types'
      fullPath: '/table/all-types'
      preLoaderRoute: typeof AuthTableAllTypesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/scheduler/workdays': {
      id: '/_auth/scheduler/workdays'
      path: '/scheduler/workdays'
      fullPath: '/scheduler/workdays'
      preLoaderRoute: typeof AuthSchedulerWorkdaysRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/scheduler/views': {
      id: '/_auth/scheduler/views'
      path: '/scheduler/views'
      fullPath: '/scheduler/views'
      preLoaderRoute: typeof AuthSchedulerViewsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/scheduler/timeline': {
      id: '/_auth/scheduler/timeline'
      path: '/scheduler/timeline'
      fullPath: '/scheduler/timeline'
      preLoaderRoute: typeof AuthSchedulerTimelineRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/scheduler/resource': {
      id: '/_auth/scheduler/resource'
      path: '/scheduler/resource'
      fullPath: '/scheduler/resource'
      preLoaderRoute: typeof AuthSchedulerResourceRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/scheduler/grouping': {
      id: '/_auth/scheduler/grouping'
      path: '/scheduler/grouping'
      fullPath: '/scheduler/grouping'
      preLoaderRoute: typeof AuthSchedulerGroupingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/scheduler/enhancements': {
      id: '/_auth/scheduler/enhancements'
      path: '/scheduler/enhancements'
      fullPath: '/scheduler/enhancements'
      preLoaderRoute: typeof AuthSchedulerEnhancementsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/kanban/timeline': {
      id: '/_auth/kanban/timeline'
      path: '/timeline'
      fullPath: '/kanban/timeline'
      preLoaderRoute: typeof AuthKanbanTimelineRouteImport
      parentRoute: typeof AuthKanbanRoute
    }
    '/_auth/kanban/swimlanes': {
      id: '/_auth/kanban/swimlanes'
      path: '/swimlanes'
      fullPath: '/kanban/swimlanes'
      preLoaderRoute: typeof AuthKanbanSwimlanesRouteImport
      parentRoute: typeof AuthKanbanRoute
    }
    '/_auth/kanban/events': {
      id: '/_auth/kanban/events'
      path: '/events'
      fullPath: '/kanban/events'
      preLoaderRoute: typeof AuthKanbanEventsRouteImport
      parentRoute: typeof AuthKanbanRoute
    }
    '/_auth/kanban/customization': {
      id: '/_auth/kanban/customization'
      path: '/customization'
      fullPath: '/kanban/customization'
      preLoaderRoute: typeof AuthKanbanCustomizationRouteImport
      parentRoute: typeof AuthKanbanRoute
    }
    '/_auth/kanban/basic': {
      id: '/_auth/kanban/basic'
      path: '/basic'
      fullPath: '/kanban/basic'
      preLoaderRoute: typeof AuthKanbanBasicRouteImport
      parentRoute: typeof AuthKanbanRoute
    }
    '/_auth/docs/ez-layout': {
      id: '/_auth/docs/ez-layout'
      path: '/docs/ez-layout'
      fullPath: '/docs/ez-layout'
      preLoaderRoute: typeof AuthDocsEzLayoutRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthKanbanRouteChildren {
  AuthKanbanBasicRoute: typeof AuthKanbanBasicRoute
  AuthKanbanCustomizationRoute: typeof AuthKanbanCustomizationRoute
  AuthKanbanEventsRoute: typeof AuthKanbanEventsRoute
  AuthKanbanSwimlanesRoute: typeof AuthKanbanSwimlanesRoute
  AuthKanbanTimelineRoute: typeof AuthKanbanTimelineRoute
  AuthKanbanIndexRoute: typeof AuthKanbanIndexRoute
}

const AuthKanbanRouteChildren: AuthKanbanRouteChildren = {
  AuthKanbanBasicRoute: AuthKanbanBasicRoute,
  AuthKanbanCustomizationRoute: AuthKanbanCustomizationRoute,
  AuthKanbanEventsRoute: AuthKanbanEventsRoute,
  AuthKanbanSwimlanesRoute: AuthKanbanSwimlanesRoute,
  AuthKanbanTimelineRoute: AuthKanbanTimelineRoute,
  AuthKanbanIndexRoute: AuthKanbanIndexRoute,
}

const AuthKanbanRouteWithChildren = AuthKanbanRoute._addFileChildren(
  AuthKanbanRouteChildren,
)

interface AuthRouteChildren {
  AuthKanbanRoute: typeof AuthKanbanRouteWithChildren
  AuthTreeRoute: typeof AuthTreeRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthDocsEzLayoutRoute: typeof AuthDocsEzLayoutRoute
  AuthSchedulerEnhancementsRoute: typeof AuthSchedulerEnhancementsRoute
  AuthSchedulerGroupingRoute: typeof AuthSchedulerGroupingRoute
  AuthSchedulerResourceRoute: typeof AuthSchedulerResourceRoute
  AuthSchedulerTimelineRoute: typeof AuthSchedulerTimelineRoute
  AuthSchedulerViewsRoute: typeof AuthSchedulerViewsRoute
  AuthSchedulerWorkdaysRoute: typeof AuthSchedulerWorkdaysRoute
  AuthTableAllTypesRoute: typeof AuthTableAllTypesRoute
  AuthTableBasicTableRoute: typeof AuthTableBasicTableRoute
  AuthTableColumnTypesRoute: typeof AuthTableColumnTypesRoute
  AuthTableCrudRoute: typeof AuthTableCrudRoute
  AuthTableGroupingRoute: typeof AuthTableGroupingRoute
  AuthTablePivotRoute: typeof AuthTablePivotRoute
  AuthTableVariantsRoute: typeof AuthTableVariantsRoute
  AuthLayoutImperativeIndexRoute: typeof AuthLayoutImperativeIndexRoute
  AuthSchedulerIndexRoute: typeof AuthSchedulerIndexRoute
  AuthSignatureIndexRoute: typeof AuthSignatureIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthKanbanRoute: AuthKanbanRouteWithChildren,
  AuthTreeRoute: AuthTreeRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthDocsEzLayoutRoute: AuthDocsEzLayoutRoute,
  AuthSchedulerEnhancementsRoute: AuthSchedulerEnhancementsRoute,
  AuthSchedulerGroupingRoute: AuthSchedulerGroupingRoute,
  AuthSchedulerResourceRoute: AuthSchedulerResourceRoute,
  AuthSchedulerTimelineRoute: AuthSchedulerTimelineRoute,
  AuthSchedulerViewsRoute: AuthSchedulerViewsRoute,
  AuthSchedulerWorkdaysRoute: AuthSchedulerWorkdaysRoute,
  AuthTableAllTypesRoute: AuthTableAllTypesRoute,
  AuthTableBasicTableRoute: AuthTableBasicTableRoute,
  AuthTableColumnTypesRoute: AuthTableColumnTypesRoute,
  AuthTableCrudRoute: AuthTableCrudRoute,
  AuthTableGroupingRoute: AuthTableGroupingRoute,
  AuthTablePivotRoute: AuthTablePivotRoute,
  AuthTableVariantsRoute: AuthTableVariantsRoute,
  AuthLayoutImperativeIndexRoute: AuthLayoutImperativeIndexRoute,
  AuthSchedulerIndexRoute: AuthSchedulerIndexRoute,
  AuthSignatureIndexRoute: AuthSignatureIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  StandaloneLayoutRoute: StandaloneLayoutRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
